name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  test_python_310:
    if: always()
    # This job runs first
    name: "ubuntu-latest3.10"
    runs-on: "ubuntu-latest3.10"
    strategy:
      fail-fast: false
      matrix:
        chunks: [1]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: arm64

      - name: "Install dependencies"
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt -c constraints.txt
          python -m pip install -U -r requirements-dev.txt coveralls -c constraints.txt
          python -m pip install -c constraints.txt -e .
          python -m pip install "qiskit-ibmq-provider" -c constraints.txt
          python -m pip install "qiskit-aer"
     
      - name: "Run tests"
        continue-on-error: true
        run: |
          EXIT_CODE=0
          for i in {1..10}; do
            echo "Chunk ${{ matrix.chunks }} (Python 3.9): Test run #$i"
            stestr run || EXIT_CODE=1
          done
          exit
      