name: Flakiness Check
on:
  # You can trigger whenever there's a push or pull request, or call it manually
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  flakiness-tests:
    name: Run Tests Multiple Times to Detect Flakiness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt -e .
          pip install -U -c constraints.txt -r requirements-dev.txt

      - name: Run tests multiple times
        run: |
          # Adjust as needed; e.g., loop 5 or 10 times
          for i in {1..5}; do
            echo "Flakiness test iteration #$i"
            # The command below can be any test command: 'make unit-test-coverage', 'make test', etc.
            make unit-test-coverage || exit 1
          done
