name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  tests:
    if: always()
    runs-on: macOS-14
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: arm64
      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt
          python -m pip install -U -r requirements-dev.txt
          python -m pip install -e .
      - name: Run tests multiple times
        run: |
          # Run the test suite 5 times in a row.
          # Adjust the upper bound (1..5) to increase or decrease the total runs.
          for i in {1..5}; do
            echo "Starting test run #$i for Python ${{ matrix.python-version }}"
            stestr run || exit 1
          done
