name: Tests
on:
  push:
    branches: [ main, 'stable/*' ]
  pull_request:
    branches: [ main, 'stable/*' ]
  merge_group:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    # Removed the old condition, replaced with always() so it runs in your fork
    if: always()
    name: macOS-arm64-tests-Python-${{ matrix.python-version }}
    runs-on: macOS-14
    strategy:
      fail-fast: false
      matrix:
        # Test Python 3.10 and 3.13 on arm64 macOS
        python-version: ["3.10", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70
        if: matrix.python-version == '3.10'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: arm64

      - name: 'Install dependencies (3.10)'
        run: |
          python -m pip install -U -r requirements.txt -c constraints.txt
          python -m pip install -U -r requirements-dev.txt -c constraints.txt
          python -m pip install -c constraints.txt -e .
        if: matrix.python-version == '3.10'
        env:
          QISKIT_NO_CACHE_GATES: 1

      - name: 'Install dependencies (3.13)'
        run: |
          python -m pip install -U -r requirements.txt -c constraints.txt
          python -m pip install -U -r requirements-dev.txt -c constraints.txt
          python -m pip install -c constraints.txt -e .
        if: matrix.python-version == '3.13'

      - name: 'Install optionals'
        run: |
          python -m pip install -r requirements-optional.txt -c constraints.txt
          python tools/report_numpy_state.py
        if: matrix.python-version == '3.10'

      - name: 'Run tests multiple times'
        run: |
          for i in {1..5}; do
            echo "Starting test run #$i for Python ${{ matrix.python-version }}"
            stestr run || exit 1
          done
