name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행
  workflow_dispatch:      # 수동으로 실행 가능

jobs:
  test_python_310:
    if: always()
    name: "macOS-arm64-tests-Python-3.10"
    runs-on: macOS-14
    strategy:
      fail-fast: false
      matrix:
        chunks: [1]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: arm64

      - name: "Install dependencies"
        run: |
          python -m pip install -U -r requirements.txt -c constraints.txt
          python -m pip install -U -r requirements-dev.txt -c constraints.txt
          python -m pip install -c constraints.txt -e .
       
      - name: "Install optionals"
        run: |
          python -m pip install -r requirements-optional.txt -c constraints.txt
          python tools/report_numpy_state.py
      - name: "Run tests"
        continue-on-error: true
        run: |
          EXIT_CODE=0
          for i in {1..10}; do
            echo "Chunk ${{ matrix.chunks }} (Python 3.10): Test run #$i"
            stestr run || EXIT_CODE=1
          done
          exit $EXIT_CODE
