name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  test_python_310:
    if: always()
    # This job runs first
    name: "macOS-arm64-tests-Python-3.8"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunks: [1]
    steps:
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt -c constraints.txt
          python -m pip install -U -r requirements-dev.txt coveralls -c constraints.txt
          python -m pip install -c constraints.txt -e .
          python -m pip install "qiskit-ibmq-provider" -c constraints.txt
          python -m pip install "qiskit-aer"
        env:
          SETUPTOOLS_ENABLE_FEATURES: "legacy-editable"
      - name: Run randomized tests
        run: make test_randomized
        env:
          RUST_BACKTRACE: 1
      - name: Create comment on failed test run
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 2645
          body: |
            Randomized tests failed at commit ${{ github.sha }}.

            _Logs_: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.


      - name: "Run tests"
        continue-on-error: true
        run: |

        # 10 runs 
          EXIT_CODE=0
          for i in {1..10}; do
            echo "Chunk ${{ matrix.chunks }} (Python 3.9): Test run #$i"
            stestr run || EXIT_CODE=1
          done
          exit

      
      

