name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  test_python_310:
    if: always()
    # This job runs first
    name: "macOS-arm64-tests-Python-3.10"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunks: [1]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip

          python -m pip install -U -r requirements.txt -c constraints.txt
          python -m pip install -U -r requirements-dev.txt coveralls -c constraints.txt
          python -m pip install -c constraints.txt -e .
 
        env:
          SETUPTOOLS_ENABLE_FEATURES: "legacy-editable"
      

      - name: "Run tests"
        continue-on-error: true
        run: |

          for i in {1..50}; do
            echo "Chunk ${{ matrix.chunk }} (Python ${{ matrix.python-version }}): Test run #$i"
            stestr run || exit 1
          done

      
      